version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
  # Container postgres:
  dev-database:
    image: postgres:15.0
    container_name: dev-database # docker container
    ports:
      - 5432:5432 # {portPC}: {portContainer}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-network

  # Container for testing purposes
  test-database:
    image: postgres:15.0
    container_name: test-database # docker container
    ports:
      - 5433:5432 # {portPC}: {portContainer}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - nestjs-network
networks:
  nestjs-network:
# docker ps

